name: CI Build (cache + artifacts + secrets)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_ENV: ci
      BUILD_DIR: dist

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Быстрый кэш для Node: либо включенный в setup-node,
      # либо actions/cache (чуть ниже — альтернативный вариант).
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          echo "APP_ENV=$APP_ENV"
          npm run build
          # для демонстрации создадим файл-лог
          echo "Build time: $(date)" > build.log

      # Загружаем артефакты (сборка + логи)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            ${{ env.BUILD_DIR }}/
            build.log

      # Пример использования секретов (создай NPM_TOKEN в Settings → Secrets and variables → Actions)
      - name: Publish to npm (dry-run)
        if: github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm whoami || echo "No auth (ok for demo)"
          # демонстрация: не публикуем по-настоящему
          npm publish --dry-run || true
