name: CI Build (artifacts + secrets MIN)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make demo files
        run: |
          mkdir -p dist
          echo "Hello from CI $(date)" > dist/index.txt
          echo "Build log at $(date)" > build.log

      - name: Check secret present (no leak)
        env:
          DUMMY: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -n "$DUMMY" ]; then echo "Secret set (length: ${#DUMMY})"; else echo "No secret set (ok for demo)"; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            dist/
            build.log
